### ISSUE TITLE
Declaration of Yiisoft\Data\Cycle\Reader\EntityReader::withLimit(int $limit): static must be compatible with Yiisoft\Data\Reader\LimitableDataInterface::withLimit(?int $limit): static

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/data-cycle#29]
### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 8.3
| Operating system | Windows 11

Yiisoft\ErrorHandler\Exception\ErrorException: Declaration of Yiisoft\Data\Cycle\Reader\EntityReader::withLimit(int $limit): static must be compatible with Yiisoft\Data\Reader\LimitableDataInterface::withLimit(?int $limit): static in C:\wamp64\www\invoice\vendor\yiisoft\data-cycle\src\Reader\EntityReader.php:79
Stack trace:
#0 [internal function]: Yiisoft\ErrorHandler\ErrorHandler->Yiisoft\ErrorHandler\{closure}()
#1 {main}

**Comment by rossaddison** [comment]
Missing a question mark '?' before int.

**Comment by samdark** [comment]
Already fixed. Do `composer update`. https://github.com/yiisoft/data-cycle/blob/master/src/Reader/EntityReader.php#L72

**Comment by rossaddison** [comment]
Problem 1
    - Root composer.json requires yiisoft/data-cycle dev-master -> satisfiable by yiisoft/data-cycle[dev-master].
    - yiisoft/data-cycle dev-master requires yiisoft/data dev-move-fixtures-to-trait -> found yiisoft/data[dev-move-fixtures-to-trait] but it conflicts with your root composer.json require (dev-master).

**Comment by samdark** [comment]
Try again.

**Comment by rossaddison** [comment]
Thanks.
